// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOfH1pnLp88T0dJHYLAOb-5n9E-l9ioGI',
    appId: '1:926172492269:android:956a8a3ae120c333cdb7e4',
    messagingSenderId: '926172492269',
    projectId: 'flyer-angebote',
    databaseURL: 'https://flyer-angebote-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flyer-angebote.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2orPREaudg6E2tti5JgBC3b_r0SZpAD8',
    appId: '1:926172492269:ios:445a70898aa96c53cdb7e4',
    messagingSenderId: '926172492269',
    projectId: 'flyer-angebote',
    databaseURL: 'https://flyer-angebote-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flyer-angebote.appspot.com',
    iosBundleId: 'com.example.flashAngebote',
  );
}
